apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  namespace: argocd
spec:
  description: Example Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: default 
    server: https://kubernetes.default.svc